name: test-network
services:
  app:
    build: app-server
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000
  proxy:
    image: nginx
    ports:
      - 8080:80
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    depends_on:
      - app
