FROM python:3.10

COPY src /src
COPY requirements.txt /requirements.txt

RUN pip install -r requirements.txt

CMD [ "uvicorn" , "src.app:app" ,"--proxy-headers", "--host", "0.0.0.0", "--port", "8000"]

